### ISSUE TITLE
DlnaLibrary缺少classes_merge_1.jar

### ISSUE THREAD

**Issue by corona18525** [uaoan/DkPlayer#2]
DlnaLibrary  libs缺少classes_merge_1.jar。无法运行
可以提供classes_merge_1.jar 用来编译参考下吗，谢谢

**Comment by uaoan** [comment]
你好 可以去发布版本那里去下载jar包 或者复制下面的地址去下载
https://github.com/uaoan/DkPlayer/releases/download/1.0/classes_merge_1.jar 

@corona18525
